create extension if not exists "pgcrypto";
-- schema from implementation plan
-- (full DDL)
create table if not exists public.studio_scenarios (id uuid primary key default gen_random_uuid(),owner_id uuid references auth.users(id) on delete cascade,title text not null,description text,level text,language text default 'en-th',is_published boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.studio_voice_profiles (id uuid primary key default gen_random_uuid(),owner_id uuid references auth.users(id) on delete cascade,name text not null,role text,language text default 'en',provider text default 'kokoro',model text,voice_id text,speed numeric default 1.0,pitch numeric default 1.0,sample_rate integer default 24000,created_at timestamptz default now());
create table if not exists public.studio_slides (id uuid primary key default gen_random_uuid(),scenario_id uuid not null references public.studio_scenarios(id) on delete cascade,slide_number integer not null,slide_key text,title text,student_text text,patient_text text,teacher_note text,audio_text text,audio_text_hash text,audio_status text default 'missing',audio_voice_profile_id uuid references public.studio_voice_profiles(id) on delete set null,current_audio_asset_id uuid,created_at timestamptz default now(),updated_at timestamptz default now(),unique (scenario_id, slide_number));
create table if not exists public.studio_audio_assets (id uuid primary key default gen_random_uuid(),scenario_id uuid not null references public.studio_scenarios(id) on delete cascade,slide_id uuid not null references public.studio_slides(id) on delete cascade,owner_id uuid references auth.users(id) on delete cascade,bucket text not null default 'scenario-audio',storage_path text not null,original_filename text,display_filename text,mime_type text,file_size integer,duration_seconds numeric,version integer default 1,is_current boolean default true,text_hash text,provider text,model text,voice_profile_id uuid references public.studio_voice_profiles(id) on delete set null,generated_by_job_id uuid,created_at timestamptz default now());
alter table public.studio_slides add constraint studio_slides_current_audio_asset_fk foreign key (current_audio_asset_id) references public.studio_audio_assets(id) on delete set null;
create table if not exists public.studio_audio_generation_jobs (id uuid primary key default gen_random_uuid(),scenario_id uuid not null references public.studio_scenarios(id) on delete cascade,slide_id uuid not null references public.studio_slides(id) on delete cascade,requested_by uuid references auth.users(id) on delete set null,input_text text not null,normalized_text text not null,text_hash text not null,provider text default 'kokoro',model text,voice_profile_id uuid references public.studio_voice_profiles(id) on delete set null,language text default 'en',speed numeric default 1.0,status text default 'queued',attempts integer default 0,error_message text,output_audio_asset_id uuid references public.studio_audio_assets(id) on delete set null,created_at timestamptz default now(),started_at timestamptz,completed_at timestamptz);
